### ISSUE TITLE
Windows 10 loT

### ISSUE THREAD

**Issue by watashimeandeu** [derekhe/waveshare-7inch-touchscreen-driver#2]
Hi, 
first off all, it's working great on debian, thank you.
It is possible to do the same to windows 10 loT?
I'm searching the drivers for weeks and this project was the only one closer.
Or anyone can redirect me, pls.

I really appreciate any help.
Thank you.

**Comment by derekhe** [comment]
Hi,
I didn't use IoT before because it is a trail thing before. This display should work on it I guess. Firstly it is a USB Hid device so I guess IoT should support it.
But only detect the USB Hid driver is not enough. We need to read from the driver and simulate the mouse behaviour. This should be a user space "driver" which can be written by C#.

**Comment by luka1995** [comment]
I am searching drivers for Windows iOT, something new?

**Comment by derekhe** [comment]
Right now there is no support for IoT. I planned to do it but now get very busy, so I didn't have a chance to go on.

**Comment by luka1995** [comment]
:/ How much time do you need for do it? and $? can you contact me: luka.penger@gmail.com

**Comment by derekhe** [comment]
@luka1995
To ask your question, I can't have an estimate about this because I don't have time to do this year. I'm focusing on an very important mobile app at this moment.

If you have capacity to write a driver, that's the best. I guess: "Firstly it is a USB Hid device so I guess IoT should support it. But only detect the USB Hid driver is not enough. We need to read from the driver and simulate the mouse behaviour. This should be a user space "driver" which can be written by C#."

Another way around, you can buy another type of screen which supports IoT. This will save you a lot of time and money.

**Comment by luka1995** [comment]
Ok, where i can find documentation for protocol or something?

**Comment by derekhe** [comment]
@luka1995 
I found the protocol here: https://github.com/ChalmersRobotics/wavesahre-7inch-touchscreen-driver/commit/4665de8b8ce2a59012afe564101c5fb0863b5032

**Comment by luka1995** [comment]
This not support multi touch?

**Comment by luka1995** [comment]
Ok I can write application in C#, but we also need driver for USB? where to get it?

**Comment by derekhe** [comment]
@luka1995 
Sorry I don't know this detail for IoT. I guess IoT have a generic driver for HID device, so you can try to find out how to read data from HID. Then use the protocol to get the touch position. Then use Windows API to simulate mouse events or touch events.

**Comment by watashimeandeu** [comment]
Sorry my delay and thank you for the fast answer derekhe.
Any progress on user driver?

**Comment by luka1995** [comment]
Looking for somebody to create driver.

**Comment by watashimeandeu** [comment]
Ok, thank you.
I never develop a driver but soon as i can i will try something and let you know.

**Comment by luka1995** [comment]
If you want to help us and develop driver, contact me for more info and payment... luka.penger@gmail.com

**Comment by watashimeandeu** [comment]
No need to pay. I have to put this working faster but i'm really busy developing the rest.

**Comment by luka1995** [comment]
I want to pay, and I need one developer to help me :) When will you have time?

**Comment by luka1995** [comment]
@watashimeandeu Something new about driver?

**Comment by watashimeandeu** [comment]
Not yet :x . I think next week i will have some time.

**Comment by derekhe** [comment]
Hi all,
I got some update from waveshare that they plan to release IoT drivers recently. Let's see what they will provide.

**Comment by luka1995** [comment]
Cool, we will see :)

**Comment by aadityadengle** [comment]
@derekhe 
do you have any more updates abt when waveshare is planning to release IoT drivers?

**Comment by derekhe** [comment]
@aadityadengle right now no. I will ask them this week.

**Comment by derekhe** [comment]
Got some update from waveshare. They are in progress. Single touch is working and multi touch is in testing now. Hope they can release as soon as possible.

**Comment by luka1995** [comment]
I hope soo :)

**Comment by aadityadengle** [comment]
That's good... :)

**Comment by derekhe** [comment]
![fqf64c ev jn m ufw 6m](https://cloud.githubusercontent.com/assets/1734077/11971465/1aa1e95a-a979-11e5-917e-2e796ac1a45e.jpg)
The highlighted models are supported in windows 10 iot without any additional drivers. You guys can have a try. Other models are not supported.
