### ISSUE TITLE
Buy Pro version driver

### ISSUE THREAD

**Issue by luka1995** [derekhe/waveshare-7inch-touchscreen-driver#9]
@derekhe 

Hi, how can I buy your driver for raspbian kernel 4+ ? which have calibration options etc..

**Comment by luka1995** [comment]
<img width="765" alt="screen shot 2015-11-18 at 17 51 41" src="https://cloud.githubusercontent.com/assets/3648001/11247604/12b38310-8e1d-11e5-8d62-cac3d394f106.png">

**Comment by derekhe** [comment]
Hi @luka1995,

Thank you for love this pro verison. I'm quite busy doing another work so this pro version is still in progress. Sorry for this.

**Comment by luka1995** [comment]
When do you expect to finish?

**Comment by derekhe** [comment]
I have no idea right now.

**Comment by Stahl80** [comment]
Hi! Im also interested in pro version!
I installed this one but when "dragging" the pointer or scrolling on webpage it keeps marking text and so on. Is that normal behavior?

**Comment by luka1995** [comment]
I'm 100% interested for pro version :)

**Comment by Stahl80** [comment]
Couldn't find anywhere else to post this. I love this driver, works perfect thanks so much for your work!
One thing I can't figure out thought. If I disconnect my LCD and connect it to my tv the signal is no longer supported. I guess it's because the drive sets the evolution to 800x480 and the tv won't accept this signal. Is there a way to add more supported resolution or get the raspberry to auto switch when connecting another display/tv?
